### ISSUE TITLE
[DOXIASITETOOLS-176] Updating from 1.7.2 to 1.7.3 compile issue

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia-sitetools#449]
**[Alex O'Ree](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=spyhunter99)** opened **[DOXIASITETOOLS-176](https://issues.apache.org/jira/browse/DOXIASITETOOLS-176?redirect=false)** and commented

I'm working on the maven pdf plugin and ran into an issue updating the dependency to 1.7.3 (was 1.7.2).

incompatible types: java.io.File cannot be converted to org.apache.maven.artifact.Artifact

The particular API call that was working with 1.7.2 and older was this...

File  skinFile =
siteTool.getSkinArtifactFromRepository( localRepository, project.getRemoteArtifactRepositories(),
decorationModel ).getFile();

final SiteRenderingContext context =
siteRenderer.createContextForSkin( skinFile, new HashMap<String, Object>( 2 ), decorationModel,
project.getName(), locale );

Looking at the list of resolved issues from JIRA, it's not obvious that there was an API change. Any ideas as to what I need to change the code to?

---
No further details from [DOXIASITETOOLS-176](https://issues.apache.org/jira/browse/DOXIASITETOOLS-176?redirect=false)
